var GAME_LEVELS = [
  ["                                    xxxxxxxxxx                                  ",
   "                                   x          x                                 ",
   "                                  x                                             ",
   "                                 x                                              ",
   "                                 xxx=         xxx                               ",
   "                                   x    xx    x                                 ",
   "                                   xx        xx                                 ",
   "                                   x          x                                 ",
   "                                xxxxxxx    xxxxxxx                              ",
   "                                x                x                              ",
   "                                x   =        =   x                              ",
   "                           xxxxxxxxxxxx    xxxxxxxxxxx                          ",
   "                          x       x            x      x                         ",
   "                         x        x     ss     x       x                        ",
   "                        x         x     xx     x        x                       ",
   "                       x          xx          xx         x                      ",
   "   x                  x           x            x          x                 x   ",
   " e x                 xxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxx                x   ",
   "   x                                      xxx             xxx               x   ",
   "   x                                      xxx             xxx               x   ",
   "   x                                      xxx             xxx               x   ",
   "   x                                      xxx               xx        x     x   ",
   "   x    @         xxx  xxxxxxxxx  xxxxxx  xxxxxx  xxxxxxxx  xxx       x     x   ",
   "   x   xxx   o   xxxx||         ||xxxxxx!!xxxxxx||        ||xxxx     xxx    x   ",
   "   x  xxxxx     xxx!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!!!xxx   xxxxx   x   ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   "],





  ["xxxxxxxxxxx                                                                                    x              ",
   "x                e                                                                             x              ",
   "x @                                                                                            x              ",
   "xxxx                                                                                           x              ",
   "x   x   o                                                                                      x              ",
   "x    x                                                                                         x              ",
   "x     x                                     xxvxvxxxvxvxxxvxvxxxvxvxxxvxxxxxx        xxxxxxxxxxx              ",
   "x      x                                                                                       x              ",
   "x       x                                                                                      x              ",
   "x        x                                                                                     x              ",
   "x         x                                                               xxx                  x              ",
   "x          x                                                            xxx x      =           x              ",
   "x           x                                                         xxx   x     xxxxxxx      x              ",
   "xxssx        x                                                      xxx     x      x           x              ",
   "xxxxxx        x                                                   xxx       x!!!!!!x           x              ",
   "xxxxxxxx       x            xxxxxxxxxxxxx                       xxx         xxxxxxxx    xxxxxxxx              ",
   "xxxxxxxxxxx     x           x!!!!!!!!!!!x                     xxx           x                  x              ",
   "x                x          x!!!!!!!!!!!x                   xxx             x                  x              ",
   "x                 x         xx|xxxxxxx|xx                 xxx               x==                x              ",
   "x       xxxxssxxxxxx                                    xxx                 x      xxxxxxxxxxxxx              ",
   "x                   x                                 xxxxx                 x                  x              ",
   "x                    x                              xxx|!|x                 x==                x              ",
   "x                     x                           xxxxx x x   xxxx    xxxxxxxxxxxxxxxxxxx      x              ",
   "x         x            x                        xxx              x          x                  x              ",
   "x         x             x                     xxx                x          x==                x              ",
   "xxxxxsssxxx              xxxxxx       xxxxxxxxx       xxxxxxx    x          x      xxxxxxxxxxxxx              ",
   "xxxxxxxxxxx                  =x!!xxx!!x=                    x!!!!x          x      xxxxxxxxxxxxx              ",
   "xxxxxxxxxxx           x                                     x!!!!x    x            xxxxxxxxxxxxx              ",
   "xxxxxxxxxxxxssssssssxxx                                     x!!!!xxsssx            xxxxxxxxxxxxx              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              "],





  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "    sss                         sss                                                                           ",
   "                                                                    sss                                       ",
   "                                                                                                              ",
   "                     sss                                                              sss                     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                      sss                                                                     ",
   "                                                                                                              ",
   " sss                                                                                                 sss      ",
   "                             sss                                              sss                             ",
   "                                                    xxxxx                                                     ",
   "                                                 xxx     xxx                                                  ",
   "                   sss                    sss  xxx         xxx                                                ",
   "                                                                     sss                                      ",
   "          sss                                                                                sss              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                               xxx                                          xxx                               ",
   "        sss                                                                                                   ",
   "                        sss        xxx                                  xxx         sss                       ",
   "                                                                                                              ",
   "                                       xxx                          xxx                                       ",
   "  sss                                                                                              sss        ",
   "                                           xxx                  xxx                                           ",
   "                                             x                  x                                             ",
   "                                             x                  x                                             ",
   "                                             x                  x                                             ",
   "                      sss                    x    o             x            sss           sss                ",
   "                                             x                  x                                             ",
   "          sss                                x                  x                                             ",
   "                                sss          x                  x                                             ",
   "                                             xssxxxxxx  xxxxxxssx                                             ",
   "                                             xxxx    x  x    xxxx                                             ",
   "                                                     x  x                                                     ",
   "                                                     x  x              sss                                    ",
   "                   sss                               x  x                                                     ",
   "                                                     x  x                                                     ",
   "                                                     x  x                                                     ",
   "     sss                          sss                x@ x                           sss               sss     ",
   "                        e                            x  x                   e                                 ",
   "                                                     xssx                                                     "],



  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                             s",
   "                                                                                                            s ",
   "                                                                                                           s  ",
   "                                                                                                          s   ",
   "s                                                                                                        s    ",
   " s                                                                                                      s     ",
   "  s                                                                                                    s      ",
   "   s                                                                                                  s       ",
   "    s                                                                                                s        ",
   "     s            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         s         ",
   "      s                                                                                            s          ",
   "       s                                                                                          s           ",
   "        s                                                                                        s            ",
   "         s                                                                                      s             ",
   "          s                                                                                    s              ",
   "           s                                       @                                          s               ",
   "            s                                                                                s                ",
   "             s                      xxxx  xxxx   xxxxxxxx   xxxx   xxxx                     s                 ",
   "              s                     x!!x  x!!x   x!!!!!!x   x!!x   x!!x                    s                  ",
   "               s                     x!!xx!!x    x!xxxx!x   x!!x   x!!x                   s                   ",
   "                s                     x!!!!x     x!x  x!x   x!!x   x!!x                  s                    ",
   "                 s                     x!!x      x!x  x!x   x!!x   x!!x                 s                     ",
   "                  s                    x!!x      x!xxxx!x   x!!!xxx!!!x                s                      ",
   "                   s                   x!!x      x!!!!!!x   x!!!!!!!!!x               s                       ",
   "                    s                  xxxx      xxxxxxxx   xxxxxxxxxxx              s                        ",
   "                     s                                                              s                         ",
   "                      s                                                            s                          ",
   "                       s        xxxx   xxxx   xxxx   xxxx   xxxx   xxxx           s                           ",
   "                        s       x!!x   x!!x   x!!x   x!!x   x!!!x  x!!x          s                            ",
   "                         s      x!!!x x!!!!x x!!!x   x!!x   x!!!!x x!!x         s                             ",
   "                          s     x!!!!x!!!!!!x!!!!x   x!!x   x!!!!!xx!!x        s                              ",
   "                           s    x!!!!!!!!!!!!!!!!x   x!!x   x!!!!!!!!!x       s                               ",
   "                            s    x!!!!!!!!!!!!!!x    x!!x   x!!xx!!!!!x      s                                ",
   "                             s   x!!!!!!xx!!!!!!x    x!!x   x!!x x!!!!x     s                                 ",
   "                              s   x!!!!x  x!!!!x     x!!x   x!!x  x!!!x    s                                  ",
   "                               ssssxxxx    xxxxssssssxxxxsssxxxx   xxxxssss                                   "]






];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
